<a href="https://colab.research.google.com/github/ChanyaphasC/data-science-bootcamp-8/blob/main/Essential_Python_for_Data_Analyst.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Essential Python for Data Analyst

- ✅control flow + function
- ✅OOP: Object Oriented Programming
- ✅try except handle error
- ✅context manager, csv, json
- ✅API
- ✅web scraping => static website
- intro to data science libaries

## Control flow & Function

In [ ]:
### function def ###
def hello(name):
    print("Hi " + name)

hello("Nina")

Hi Nina


In [ ]:
# lambda function -> shortcut to define function
hello = lambda name: print("Hi " + name)

In [ ]:
### control flow ###
# if for while

In [ ]:
# if elif else
def grading(score):
    """
    this function return grade for a student
    """
    if score >= 70:
        return "Distinction"
    elif score >= 60:
        return "Merit"
    elif score >= 50:
        return "Passed"
    else:
        return "Failed"

grading(61)

'Merit'

In [ ]:
# return value from a function
def add_two_num(x,y):
    return x+y

result = add_two_num(10, 15)
print(result)

25


In [ ]:
# for loop
nums = [1,2,3,4,5]  ## => [2,4,6,8,10]

new_nums = []   # empty list

for num in nums:
    new_nums.append(num*2)

print(new_nums)

[2, 4, 6, 8, 10]


In [ ]:
# list comprehension
x = [1,2,3,4,5]
y = [num*2 for num in nums]
print(y)

[2, 4, 6, 8, 10]


In [ ]:
## program to check odd/even numbers
nums = [34,50,22,21,28]
for num in nums:
    if num % 2 == 0:
        print(f"{num} is even")
    else:
        print(f"{num} is odd")

34 is even
50 is even
22 is even
21 is odd
28 is even


In [ ]:
# while loop
count = 0
while count < 5:
    print("hello")
    # this line is very important
    count += 1

hello
hello
hello
hello
hello


In [ ]:
x = 1
x += 1
x += 1
x += 1
x -= 3
x *= 5
x *= 2
x /= 4
print(x)

2.5


In [ ]:
from pygments.lexers import guess_lexer
# get input from a user
def animal_guessing():
    set_animal = "hippo"
    answers = []
    while True:
        guess = input("Guess the animal: ")
        answers.append(guess)
        if guess == set_animal:
            print("Hooray! correct answer")
            print(f"Logs: {answers}")
            break
        elif guess == "quit":
            print("See you next time")
            break
        else:
            print("Nope! please try again")

animal_guessing()

Guess the animal: dog
Nope! please try again
Guess the animal: cat
Nope! please try again
Guess the animal: hippo
Hooray! correct answer
Logs: ['dog', 'cat', 'hippo']


## OOP

In [ ]:
### OOP => Object Oriented Programming ###

In [ ]:
class Apple:
    def __init__(self, size, price, color):
        self.size = size
        self.price = price
        self.color = color

apple1 = Apple("medium", 5 ,"red")

print(apple1.size, apple1.price, apple1.color)

medium 5 red


In [ ]:
## Dog
class Dog:
    def __init__(self, name, age, breed):  # initialize การประกาศค่าตัวแปร
        self.name = name
        self.age = age
        self.breed = breed

    ## dog methods (functions)
    def sit(self):
        print("I'm sitting now.")

    def sleep(self):
        print("I'm sleeping now.")

    def get_older(self, year):
        self.age += year


In [ ]:
## Dog method
dog1 = Dog("Milo", 3, "shihuahua")
dog1.get_older(2)
print(dog1.age)

5


In [ ]:
text = "a duck walk into a bar"

In [ ]:
## string method
text.split()

['a', 'duck', 'walk', 'into', 'a', 'bar']

In [ ]:
"HELLO WORLD".lower()

'hello world'

In [ ]:
## list method
emp_list = []

emp_list.append("apple")
emp_list.append("banana")

emp_list

['apple', 'banana']

> Python Class => OOP
- Class => attribute: name, age, breed
- Class => method: function => sit, sleep, get older

In [ ]:
class Person:
    def __init__(self, name):
        self.name = name

## Superclass ขยาย feature ของตัว base อันเก่า
class Employee(Person):
    def __init__(self, name, company, position):
        super().__init__(name)
        self.name = name
        self.company = company
        self.position = position
    def greeting(self):
        print(f"Hi my name is {self.name} and I work for {self.company}.")

In [ ]:
ps1 = Person("Nina")
ps2 = Employee("John", "Google", "Data Analyst")
ps2.greeting()

Hi my name is John and I work for Google.


> Superclass extend feature from base class

## Try except handle error

In [ ]:
## try except block
try:
    1/0
except ZeroDivisionError:
    print("Cannot divide by zero")
except NameError:
    print("Variable not found in our environment")
else:
    print("OK")
finally:
    print("End")

Cannot divide by zero
End


In [ ]:
## try except SyntaxError
try:
    eval('print(1+5 ')
except:
    print("Syntax error")

Syntax error


## Context manager, csv, json

In [ ]:
! pwd   # print working directry

/content


In [ ]:
! ls

friend.csv  sample_data


In [ ]:
! echo hello world

hello world


In [ ]:
! cat friend.csv    # concatenate show content in this file

id,name,age,company
1,toy,30,Google
2,top,3,Amazon
3,jane,25,Microsoft
4,john,28,Meta
5,anna,29,Anaconda

In [ ]:
import csv

In [ ]:
# open csv file using read mode
file = open("friend.csv", "r")

In [ ]:
# read content in this file
data = csv.reader(file)

In [ ]:
for row in data:
    print(row)

['id', 'name', 'age', 'company']
['1', 'toy', '30', 'Google']
['2', 'top', '3', 'Amazon']
['3', 'jane', '25', 'Microsoft']
['4', 'john', '28', 'Meta']
['5', 'anna', '29', 'Anaconda']


In [ ]:
# close file
file.close()

In [ ]:
## pandas
import pandas as pd

# import csv
df = pd.read_csv("friend.csv")

# export csv
df.to_csv("haha.csv")


In [ ]:
## context manager => with
## use to open data file ไม่ต้องมีคำสั่งในการปิดไฟล์ เพราะน้องปิดได้เองเลย

In [ ]:
# import csv
from csv import reader, writer
result = []

with open("friend.csv", "r") as file:
    data = csv.reader(file)
    for row in data:
        result.append(row)

result

[['id', 'name', 'age', 'company'],
 ['1', 'toy', '30', 'Google'],
 ['2', 'top', '3', 'Amazon'],
 ['3', 'jane', '25', 'Microsoft'],
 ['4', 'john', '28', 'Meta'],
 ['5', 'anna', '29', 'Anaconda']]

In [ ]:
## write mode
import csv

header = ["id", "course", 'students']
body_data = [
    [1, "data science", 30],
    [2, "maketing", 28],
    [3, "power BI", 35]
]

with open("courses.csv", "w") as file:
    writer = csv.writer(file)
    writer.writerow(header)     # เขียนทีละแถว
    writer.writerows(body_data)     # เขียนพร้อมกันหลายแถว

In [ ]:
! cat courses.csv

id,course,students
1,data science,30
2,maketing,28
3,power BI,35


In [ ]:
try:
    with open("courses.csv", "r") as file:
        data = csv.reader(file)
        for row in data:
            print(row)
except FileNotFoundError:
    print("Please check file name again.")
else:
    print("Open file successfully.")

['id', 'course', 'students']
['1', 'data science', '30']
['2', 'maketing', '28']
['3', 'power BI', '35']
Open file successfully.


In [ ]:
! cat customer.json

{
                "name": "nina",
                "age": 21,
                "company": "Samsung",
                "movie_lover": true,
                "movie": ["Aquaman", "Maze runner"]

}

In [ ]:
import json

with open("customer.json", "r") as file:
    customer = json.load(file)      # functio load cpntent in this file

print(customer, type(customer))

{'name': 'nina', 'age': 21, 'company': 'Samsung', 'movie_lover': True, 'movie': ['Aquaman', 'Maze runner']} <class 'dict'>


In [ ]:
## dict => json
book = {
    "name": "How to be better at almost everything",
    "year": 2018,
    "author": "Pat Flynn",
    "favorite": True,
}

with open("book.json", "w") as file:
    json.dump(book, file)
    print("Create file successfully!")

Create file successfully!


In [ ]:
! cat book.json

{"name": "How to be better at almost everything", "year": 2018, "author": "Pat Flynn", "favorite": true}

## API

In [ ]:
# API => Application Programming Interface
# Communication between two machines

# request-response

# import requests
# url = "https://swapi.dev/api/people/1"
# response = requests.get(url)

from requests import get
url = "https://swapi.dev/api/people/1"
resp = get(url)

## if success, OK 200
resp.status_code

## see information
resp.json()["name"]

'Luke Skywalker'

**HTTP response status codes**

1.Informational responses (100 – 199)

2.Successful responses (200 – 299)

3.Redirection messages (300 – 399)

4.Client error responses (400 – 499)

5.Server error responses (500 – 599)



In [ ]:
import requests
import time

characters = []

for i in range(5):
    url = f"https://swapi.dev/api/people/{i+1}"
    resp = requests.get(url)

    if resp.status_code == 200:
        json_data = resp.json()
        characters.append(
            (json_data["name"],
             json_data["height"])
        )

    # break a second
    time.sleep(1)

print(characters)

[('Luke Skywalker', '172'), ('C-3PO', '167'), ('R2-D2', '96'), ('Darth Vader', '202'), ('Leia Organa', '150')]


## Web scraping

In [ ]:
## install new library on google colab
# pip => package manager in Python

! pip install gazpacho

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for gazpacho: filename=gazpacho-1.1-py3-none-any.whl size=7461 sha256=7f85e11abea993f584e14a814a32d8596a41a0af9761870b02fe62308aec99c0
  Stored in directory: /root/.cache/pip/wheels/9b/bf/9f/8c8849499462415fa5cdf0d9edb1103c189bdbece90c51488e
Successfully built gazpacho


In [ ]:
! pip list | grep "^g"

gast                             0.5.4
gazpacho                         1.1
gcsfs                            2023.6.0
gdown                            4.6.6
geemap                           0.28.2
gensim                           4.3.2
geocoder                         1.38.1
geographiclib                    2.0
geopandas                        0.13.2
geopy                            2.3.0
gin-config                       0.5.0
glob2                            0.7
google                           2.0.3
google-api-core                  2.11.1
google-api-python-client         2.84.0
google-auth                      2.17.3
google-auth-httplib2             0.1.1
google-auth-oauthlib             1.0.0
google-cloud-bigquery            3.12.0
google-cloud-bigquery-connection 1.12.1
google-cloud-bigquery-storage    2.22.0
google-cloud-core                2.3.3
google-cloud-datastore           2.15.2
google-cloud-firestore           2.11.1
google-cloud-functions           1.13.3
google-cloud-iam

In [ ]:
# import function
from gazpacho import Soup

In [ ]:
## web scraping basics
url = "https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc"

html = requests.get(url)

In [ ]:
imdb = Soup(html.text)

In [ ]:
imdb.find("h3")

In [ ]:
titles = imdb.find("h3", {"class": "ipc-title__text"})

# clean_titles = []

# for title in titles:
#     clean_titles.append(title.strip())

# list comprehension
clean_titles = [title.strip() for title in titles]

clean_titles

In [ ]:
titles = imdb.find("h3", {"class": "ipc-title__text"})

if titles is not None:
    clean_titles = [title.strip() for title in titles]
else:
    # Handle the case where no titles were found
    print("No titles found.")


No titles found.


In [ ]:
## get rating from the website
## div: ratings-imdb-rating

ratings = imdb.find("div", {"class": "ipc-rating-star--voteCount"})


clean_ratings = [ratings.strip() for rating in ratings]

clean_ratings

In [ ]:
import pandas as pd

# create dataframe
movie_database = pd.DataFrame(data = {
    "title": clean_title,
    "rating": clean_ratings
})

# print first five rows
movie_database.head

## Intro to Data Science Libraries
- numpy
- pandas
- sklearn (machine learning)
- statsmodel (statistics)

> Numpy Documents: https://numpy.org/doc/

### Numpy

In [ ]:
# numerical python
# very fast

import numpy as np
nums =[1,2,3,4,5]

In [ ]:
nums = np.array(nums)

numpy.ndarray

In [ ]:
# STATISTICS CALCULATION
nums.sum()
nums.mean()
nums.std()
np.median(nums)
np.sum(nums)

15

In [ ]:
np.arange(10) + 1   # range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.linspace(0, 10, num=20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
# 2d array
n2 = np.array([
    [1,2],
    [3,4]
])

print(n2, type(n2))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [2]:
import numpy as np

In [3]:
# matrix * matrix
# .dot notation
m1 = np.array([[1,2], [5,5]])
m2 = np.array([[4,2], [1,2]])
np.dot(m1, m2)

array([[ 6,  6],
       [25, 20]])

### Pandas

In [4]:
# import pandas
# manage dataframe
import pandas as pd

In [5]:
# read data from csv file
url = "https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv"

mtcars = pd.read_csv(url)

In [9]:
mtcars.info

<bound method DataFrame.info of                   model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4   

In [10]:
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [17]:
df = mtcars[["mpg", "model", "hp"]].tail()

In [18]:
df["mpg_double"] = df["mpg"] * 2

In [19]:
df.head()

mpg           model   hp  mpg_double
27  30.4    Lotus Europa  113        60.8
28  15.8  Ford Pantera L  264        31.6
29  19.7    Ferrari Dino  175        39.4
30  15.0   Maserati Bora  335        30.0
31  21.4      Volvo 142E  109        42.8

In [26]:
colnames = list(df.columns)
colnames[0] = "new_model"
df.columns = colnames

In [27]:
df.head()

new_model           model   hp  mpg_double
27       30.4    Lotus Europa  113        60.8
28       15.8  Ford Pantera L  264        31.6
29       19.7    Ferrari Dino  175        39.4
30       15.0   Maserati Bora  335        30.0
31       21.4      Volvo 142E  109        42.8

In [32]:
# filter
mtcars[(mtcars["mpg"] > 30) & (mtcars["hp"] > 100)]

model   mpg  cyl  disp   hp  drat     wt  qsec  vs  am  gear  carb
27  Lotus Europa  30.4    4  95.1  113  3.77  1.513  16.9   1   1     5     2

In [34]:
# pandas .query()
# condition used to filter dataframe
mtcars.query(" mpg > 30 and hp > 100 ")

model   mpg  cyl  disp   hp  drat     wt  qsec  vs  am  gear  carb
27  Lotus Europa  30.4    4  95.1  113  3.77  1.513  16.9   1   1     5     2

In [36]:
# aggregate + group by
store = pd.read_csv("/content/Copy of store.csv")

In [38]:
col_names = list(store.columns)

In [41]:
clean_col_names = [col.lower().replace(" ", "_").replace("-", "_") for col in col_names]

# clean column names
store.columns = clean_col_names
store.head()

In [50]:
segcat = store.groupby(["segment", "category"])["sales"].sum().reset_index()
segcat

# segcat.to_csv("agg_data.csv")

In [56]:
# aggregate
store.groupby("segment")["sales"].\
    agg(["sum", "mean", "std"]).\
    reset_index()

segment           sum        mean         std
0     Consumer  1.161401e+06  223.733644  585.516175
1    Corporate  7.061464e+05  233.823300  599.410408
2  Home Office  4.296531e+05  240.972041  755.516379

In [ ]:
## read data from sql database
import sqlite3
import pandas as pd

## create connection
con = sqlite3.connect("chinook.db")

df = pd.read_sql("SELECT * FROM customers WHERE country = 'USA'", con)

## close connection
con.close

df.head()

### Sklearn Statistics

In [64]:
## sklearn basics
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.model_selection import train_test_split
import pandas as pd

# read data
url = "https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv"

mtcars = pd.read_csv(url)

# prepare data
X = mtcars.drop(["model", "mpg"], axis=1)
y = mtcars["mpg"]

# split data
# set.seed(42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

# train model
model = BaggingRegressor()
model.fit(X_train, y_train)

# prediction
p = model.predict(X_test)

# R squared
model.score(X_test, y_test)

# MAE mean absolute error
# mean(abs(y_test - p))
np.mean(np.abs(y_test - p))

# MSE mean square error
np.mean((y_test - p)**2)


5.4636499999999915

In [65]:
p

array([19.89, 11.7 , 15.03, 28.73, 21.37, 18.8 , 15.2 , 30.28])

In [66]:
import pickle

with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)